name: to_do_list_app
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  hive_cache_manager: ^0.0.1
  uuid: ^4.4.0
  intl: ^0.19.0
  animate_do: ^3.3.4
  panara_dialogs: ^0.1.4
  lottie: ^3.1.0
  flutter_slider_drawer: ^2.1.3
  flutter_cupertino_date_picker_fork: ^1.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.9
  hive_generator: ^2.0.1

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
  assets:
    - assets/images/
    - assets/icons/
      